apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jsserver
  labels:
    app: jsserver
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jsserver
      tier: backend
  template:
    metadata:
      labels:
        app: jsserver
        tier: backend
    spec:
      containers:
      - name: jsserver
        image: srlucas/hello-js:v1.1
        ports:
        - containerPort: 3000
